// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRCt_QzxrMdfbOTOAkxtDQ03HXzUXU3VI',
    appId: '1:241030368248:web:7e3d6bfa7d9fa14fdde40d',
    messagingSenderId: '241030368248',
    projectId: 'projexity-13eac',
    authDomain: 'projexity-13eac.firebaseapp.com',
    storageBucket: 'projexity-13eac.appspot.com',
    measurementId: 'G-ZS06NWZ7FM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBby0aCirgrlgeogHG6Her5sKSqupWcyek',
    appId: '1:241030368248:android:e422ce940394b946dde40d',
    messagingSenderId: '241030368248',
    projectId: 'projexity-13eac',
    storageBucket: 'projexity-13eac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK8PzD58OYwcziTwzCWiXvCgMGoPgnZ1g',
    appId: '1:241030368248:ios:bc12156b64083960dde40d',
    messagingSenderId: '241030368248',
    projectId: 'projexity-13eac',
    storageBucket: 'projexity-13eac.appspot.com',
    iosClientId: '241030368248-mou8f7bje5n3jaiek5mialbms54cc2t8.apps.googleusercontent.com',
    iosBundleId: 'com.example.projexity',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDK8PzD58OYwcziTwzCWiXvCgMGoPgnZ1g',
    appId: '1:241030368248:ios:1722b0e8aacb3903dde40d',
    messagingSenderId: '241030368248',
    projectId: 'projexity-13eac',
    storageBucket: 'projexity-13eac.appspot.com',
    iosClientId: '241030368248-ebiivie36fo0puq0lr9u924pi2ajk79f.apps.googleusercontent.com',
    iosBundleId: 'com.example.projexity.RunnerTests',
  );
}
